theme: jekyll-theme-cayman
title: "SwiFT Store Management (OOP Project)"
description: "A C++ language project which covers all the basic & some advance concepts of OOP & C++11, using DevC++"
show_downloads: true
